POST  http://172.17.18.158:3000/api/auth/register
Content-Type: application/json
Authorization: Bearer asdfsadf

{
    "username": "a",
    "password": "aa",
    "email": "ád@mgail.com"
}

###
POST  http://172.17.18.158:3000/api/auth/login
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}


###
POST  http://172.17.18.158:3000/post/create
Content-Type: application/json
Authorization: Bearer asdfsadf

{
    "title": "a",
    "description": "a",
    "userId":"6357566677a97146280bb36b",
}

###
POST  http://172.17.18.158:3000/upload1
Content-Type: application/json

{
    "title": "a",
    "description": "a"
}

